on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: beanstats
